### ISSUE TITLE
Cannot implement didSelectRowAtIndexPath in main controller to jump to another view controller

### ISSUE THREAD

**Issue by nqhuycmc** [kingiol/XCMultiSortTableView#1]
I implemented this function in main controller, but it cant go to this function
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
     ViewStockDetails *viewStockDetails = [[ViewStockDetails alloc] init];
     ...
     [self.navigationController pushViewController:viewStockDetails animated:YES];
}
instead of this, it jump to didSelectRowAtIndexPath on XCMultiSortTableView.m

**Comment by ils-shantanuk** [comment]
XCMultiSortTableView overrides the default delegate method. You will have to write your code in the delegate method of XCMultiSortTableView

**Comment by kingiol** [comment]
now add new delegate protocol, you can find in demo project:
- (void)tableViewWithType:(MultiTableViewType)tableViewType didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
