### ISSUE TITLE
求助！！！

### ISSUE THREAD

**Issue by ponymuch** [kingiol/XCMultiSortTableView#2]
in OC:
![image](https://cloud.githubusercontent.com/assets/10826321/7218610/24ec541c-e6ac-11e4-84ce-f1d825b3ef75.png)
in Swift:
![d7ymdr_ _u qoa4bh17g7](https://cloud.githubusercontent.com/assets/10826321/7218618/4c3e9444-e6ac-11e4-902d-da8d3dded6ea.jpg)
Error:
![j7zd0 qw g8 013_hd7pkg](https://cloud.githubusercontent.com/assets/10826321/7218628/8c78afa4-e6ac-11e4-9324-e038053630c3.jpg)

Thanks.

**Comment by kingiol** [comment]
you should write like this:

@objc(arrayDataForContentInTableView:InSection:)
    func arrayDataForContentInTableView(tableView: XCMultiTableView!, inSection section: UInt) -> [AnyObject]! {
        return [""]
    }

```
@objc(arrayDataForLeftHeaderInTableView:InSection:)
func arrayDataForLeftHeaderInTableView(tableView: XCMultiTableView!, inSection section: UInt) -> [AnyObject]! {
    return [""]
}
```
