### ISSUE TITLE
Need to add label or some text on Header of Left Table View

### ISSUE THREAD

**Issue by phuc24111981** [kingiol/XCMultiSortTableView#3]
Dear King,
Thank you for your XCMultiSortTableView, it's very good :)
But please help me just 1 issue :
I need to add a label to header of the LeftTableView (or some way to add some text there)
Can i do that ? Teach me please :)
Thank you,
Best luck for you.
![screen shot 2015-06-11 at 4 07 20 pm](https://cloud.githubusercontent.com/assets/12842869/8103892/7585d046-1056-11e5-9990-a1b700b6080a.jpg)

**Comment by kingiol** [comment]
Now support
